[build]
builder = "dockerfile"

[deploy]
startCommand = "echo 'This will be overridden by individual services'"

# Backend service configuration
[[services]]
name = "backend"
source = "backend"

[services.build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[services.deploy]
startCommand = "java $JAVA_OPTS -jar app.jar"

# Frontend service configuration  
[[services]]
name = "frontend"
source = "frontend"

[services.build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"