# Backend service configuration
[[services]]
name = "backend"
source = "backend"

[services.build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile"

# Frontend service configuration  
[[services]]
name = "frontend"  
source = "frontend"

[services.build]
builder = "dockerfile"
dockerfilePath = "frontend/Dockerfile"