spring:
  application:
    name: backend

  datasource:
    url: jdbc:h2:file:./data/backend;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9092
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
  show-actuator: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.demo.backend: DEBUG
    org.springframework.web: INFO

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false

  h2:
    console:
      enabled: false

springdoc:
  swagger-ui:
    enabled: false

logging:
  level:
    com.demo.backend: INFO
    root: WARN